language: python

python:
  - "3.5"

install:
  - pip install flake8 'pylint<2.0'

script:
- flake8 --max-line-length=120 --exclude=./setup.py,./instascrape/compat.py,./web/compat.py,./instascrape/endpoints/__init__.py
- pylint -E instascrape web

branches:
  only:
    - master
